server:
  port: 7002
dubbo:
  application:
    name: dubboProvider
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: true
  protocol:
    port: 17002
    name: dubbo
  metadata-report:
    address: zookeeper://127.0.0.1:2181