server:
  port: 7003
dubbo:
  application:
    name: dubboProvider
    id: nmsl
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: true
  protocol:
    port: 17003
    name: dubbo
  metadata-report:
    address: zookeeper://127.0.0.1:2181